using Nest;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.PageObjects;
using SeleniumExtras.WaitHelpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace HT_Design_Pattern.PageObjects
{
    public class InboxPage 
    {
        public InboxPage() 
        {
            PageFactory.InitElements(BaseTest.driver, this);
        }

        //TODO long and autogenerated xpath
        public IWebElement CommposeBoxField => BaseTest.driver.FindElement(By.XPath("//div[@jscontroller='eIu7Db']"));
        
        public WebDriverWait wait = new WebDriverWait(BaseTest.driver, TimeSpan.FromSeconds(50));
        public IWebElement SenderMailField => BaseTest.driver.FindElement(By.CssSelector("input[role=combobox]"));
        public IWebElement SubjectField => BaseTest.driver.FindElement(By.Name("subjectbox"));
        public IWebElement TextBoxField => BaseTest.driver.FindElement(By.XPath("//div[@aria-label='Message Body']"));
        public IWebElement SaveCloseField => BaseTest.driver.FindElement(By.XPath("//img[@alt='Close']"));


        public void Compose(string senderMail, string subject, string textbox)
        {
            //senderMail = "shahadnaz807@gmail.com";
            //subject = "Sample Subject";
            //textbox = "Shahad Mail";

            //CommposeBoxField.Click();
            wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(CommposeBoxField));
            var CommposeBox = new Button(CommposeBoxField);
            CommposeBox.Click();
            wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementToBeClickable(SenderMailField));
            SenderMailField.SendKeys(senderMail); 
            SubjectField.SendKeys(subject); 
            TextBoxField.SendKeys(textbox); 
        }

        public void SaveCloseClick()
        {
            //SaveCloseField.Click();
            var SaveCloseButton = new Button(SaveCloseField);
            SaveCloseButton.Click();
        }



    }
}
